# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "80394bd99ceb91c1f20019f9a91bd697"
application_url = "https://syndication-pete-phantom-shark.trycloudflare.com"
embedded = true
name = "account-dev"
handle = "account-dev-1"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://syndication-pete-phantom-shark.trycloudflare.com/auth/callback",
  "https://syndication-pete-phantom-shark.trycloudflare.com/auth/shopify/callback",
  "https://syndication-pete-phantom-shark.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
